//
//  HeroesListWorker.swift
//  MarvelHeroes
//
//  Created by Joel Sene on 29/01/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HeroesListWorker
{
    func doHeroesList(nextPage: Int, result: @escaping(Result<HeroArray, Error>) -> Void)
  {
        let apiClient = MarvelAPIClient(publicKey: Keys.publicKey.rawValue,
                                        privateKey: Keys.secretKey.rawValue)
    
    apiClient.send(GetHeroes(limit: 99, offset: nextPage)) { response in
        switch response {
        case .success(let heroes):
            debugPrint(heroes)
            let model = HeroArray(heroList: heroes.results)
            result(.success(model))
        case .failure(let error):
            result(.failure(error))
        }
    }
  }
}
