//
//  HeroesListPresenter.swift
//  MarvelHeroes
//
//  Created by Joel Sene on 29/01/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HeroesListPresentationLogic
{
  func presentHeroesList(response: HeroesList.Models.Response)
    func showAlert(message: String)
}

class HeroesListPresenter: HeroesListPresentationLogic
{
    
  weak var viewController: HeroesListDisplayLogic?
  
  // MARK: Do something
  
  func presentHeroesList(response: HeroesList.Models.Response)
  {
    let viewModel = HeroesList.Models.ViewModel(heroList: response.heroList)
    viewController?.displayHeroesList(viewModel: viewModel)
  }
    
    func showAlert(message: String) {
        viewController?.displayAlert(message: message)
    }
    
}
