//
//  HeroesListInteractor.swift
//  MarvelHeroes
//
//  Created by Joel Sene on 29/01/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HeroesListBusinessLogic
{
    func doHeroesList(request: HeroesList.Models.Request)
}

protocol HeroesListDataStore
{
    var heroList: HeroArray? { get set }
}

class HeroesListInteractor: HeroesListBusinessLogic, HeroesListDataStore
{
    var heroList: HeroArray?
    var presenter: HeroesListPresentationLogic?
    var worker: HeroesListWorker?
    
    // MARK: Do something
    
    func doHeroesList(request: HeroesList.Models.Request)
    {
        
        worker = HeroesListWorker()
        worker?.doHeroesList(nextPage: request.offset) { [weak self] (result) in
            switch result {
            case .success(let heroesList):
                DispatchQueue.main.async {
                    self?.heroList = heroesList
                    let model = HeroesList.Models.Response(heroList: heroesList)
                    self?.presenter?.presentHeroesList(response: model)
                }
            case .failure(let error):
                debugPrint(error.localizedDescription)
            }
        }
    }
}
